name: Build and tests
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version:
          - 1.11.x
          - 1.12.x
          - 1.13.x
          - 1.14.x
    runs-on: ubuntu-latest

    env:
      GOPROXY: https://proxy.golang.org

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Get programs
        run: |
          export GOBIN=$HOME/bin
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.19.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          GOOS=linux go build -o taifun.linux
          GOOS=windows go build -o taifun.windows
          GOOS=darwin go build -o taifun.darwin

      - name: Run tests
        run: |
          export PATH=$HOME/bin:$PATH
          go test ./...
